apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp-rc
  template:
    metadata:
      name: myapp-rc
      labels:
        app: myapp-rc
    spec:
      containers:
        - name: myapp-rc
          image: nginx
          ports:
            - containerPort: 80
